process.env.NODE_ENV = 'test'
process.env.SUPABASE_URL = process.env.SUPABASE_URL || 'https://example.supabase.co'
process.env.SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY || 'test-publishable-key'
process.env.SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || 'test-service-role-key'
process.env.IMGBB_API_KEY = process.env.IMGBB_API_KEY || 'test-imgbb-key'
process.env.IMGBB_TIMEOUT_MS = process.env.IMGBB_TIMEOUT_MS || '15000'
