begin;

alter table public.event_categories
  add column if not exists participants_per_registration smallint not null default 1;

alter table public.event_categories
  drop constraint if exists event_categories_participants_per_registration_valid;

alter table public.event_categories
  add constraint event_categories_participants_per_registration_valid
  check (participants_per_registration in (1, 2));

-- Preserve every existing category as individual, except an already-created
-- category explicitly named Torneo/Torneos.
update public.event_categories
set participants_per_registration = 2,
    updated_at = now()
where lower(trim(name)) in ('torneo', 'torneos')
  and participants_per_registration <> 2;

create table if not exists public.event_registration_groups (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  created_by_user_id uuid not null references public.profiles(id),
  created_at timestamptz not null default now()
);

alter table public.event_registrations
  add column if not exists registration_group_id bigint;

alter table public.event_registrations
  drop constraint if exists event_registrations_registration_group_id_fkey;

alter table public.event_registrations
  add constraint event_registrations_registration_group_id_fkey
  foreign key (registration_group_id)
  references public.event_registration_groups(id)
  on delete cascade;

create index if not exists event_registrations_registration_group_idx
  on public.event_registrations(registration_group_id)
  where registration_group_id is not null;

alter table public.event_registration_groups enable row level security;
revoke all on table public.event_registration_groups from anon, authenticated;
revoke all on sequence public.event_registration_groups_id_seq from anon, authenticated;

create or replace function private.rebalance_event_waitlist(p_event_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_capacity integer;
  v_confirmed integer;
  v_available integer;
  v_waitlist_offset integer;
  v_unit record;
begin
  select capacity
  into v_capacity
  from public.events
  where id = p_event_id
  for update;

  if not found then
    raise exception 'event_not_found';
  end if;

  select count(*)::integer
  into v_confirmed
  from public.event_registrations
  where event_id = p_event_id
    and status_code = 'confirmed';

  v_available := greatest(v_capacity - v_confirmed, 0);

  for v_unit in
    select
      coalesce('group:' || registration_group_id::text, 'registration:' || id::text) as unit_key,
      array_agg(id order by id) as registration_ids,
      count(*)::integer as participant_count,
      min(waitlist_position) as first_position
    from public.event_registrations
    where event_id = p_event_id
      and status_code = 'waitlisted'
    group by coalesce('group:' || registration_group_id::text, 'registration:' || id::text)
    order by min(waitlist_position), min(id)
  loop
    exit when v_unit.participant_count > v_available;

    update public.event_registrations
    set status_code = 'confirmed',
        waitlist_position = null,
        updated_at = now()
    where id = any(v_unit.registration_ids);

    v_available := v_available - v_unit.participant_count;
  end loop;

  select coalesce(max(waitlist_position), 0) + count(*)::integer + 1
  into v_waitlist_offset
  from public.event_registrations
  where event_id = p_event_id
    and status_code = 'waitlisted';

  with reordered as (
    select
      id,
      v_waitlist_offset + row_number() over (order by waitlist_position, id)::integer
        as next_position
    from public.event_registrations
    where event_id = p_event_id
      and status_code = 'waitlisted'
  )
  update public.event_registrations registration
  set waitlist_position = reordered.next_position
  from reordered
  where registration.id = reordered.id;

  update public.event_registrations
  set waitlist_position = waitlist_position - v_waitlist_offset,
      updated_at = now()
  where event_id = p_event_id
    and status_code = 'waitlisted'
    and waitlist_position > v_waitlist_offset;
end;
$$;

revoke all on function private.rebalance_event_waitlist(bigint)
  from public, anon, authenticated;

create or replace function public.register_pair_for_event(
  p_event_id bigint,
  p_companion_user_id uuid
)
returns public.event_registrations
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_event public.events;
  v_group_id bigint;
  v_confirmed_count integer;
  v_waitlist_start integer;
  v_status_code text;
  v_result public.event_registrations;
  v_profile record;
begin
  if v_user_id is null then
    raise exception 'authentication_required';
  end if;

  if p_companion_user_id is null or p_companion_user_id = v_user_id then
    raise exception 'invalid_companion';
  end if;

  select event.*
  into v_event
  from public.events event
  join public.event_categories category on category.id = event.category_id
  where event.id = p_event_id
    and category.participants_per_registration = 2
  for update of event;

  if not found then
    if exists (select 1 from public.events where id = p_event_id) then
      raise exception 'companion_not_allowed';
    end if;
    raise exception 'event_not_found';
  end if;

  perform private.assert_event_accepts_registrations(v_event);

  for v_profile in
    select id, event_registration_blocked, event_registration_blocked_until
    from public.profiles
    where id in (v_user_id, p_companion_user_id)
  loop
    if coalesce(v_profile.event_registration_blocked, false)
      and (v_profile.event_registration_blocked_until is null
        or v_profile.event_registration_blocked_until > now()) then
      raise exception 'event_registration_forbidden' using detail = v_profile.event_registration_blocked_until::text;
    end if;
  end loop;

  if (select count(*) from public.profiles where id in (v_user_id, p_companion_user_id)) <> 2 then
    raise exception 'profile_not_found';
  end if;

  if exists (
    select 1
    from public.event_registrations
    where event_id = p_event_id
      and user_id in (v_user_id, p_companion_user_id)
  ) then
    raise exception 'registration_already_exists';
  end if;

  select count(*)::integer
  into v_confirmed_count
  from public.event_registrations
  where event_id = p_event_id
    and status_code = 'confirmed';

  if v_event.capacity - v_confirmed_count >= 2 then
    v_status_code := 'confirmed';
    v_waitlist_start := null;
  else
    v_status_code := 'waitlisted';
    select coalesce(max(waitlist_position), 0) + 1
    into v_waitlist_start
    from public.event_registrations
    where event_id = p_event_id
      and status_code = 'waitlisted';
  end if;

  insert into public.event_registration_groups(event_id, created_by_user_id)
  values (p_event_id, v_user_id)
  returning id into v_group_id;

  insert into public.event_registrations(
    event_id, user_id, status_code, waitlist_position, registration_group_id
  )
  values
    (p_event_id, v_user_id, v_status_code, v_waitlist_start, v_group_id),
    (
      p_event_id,
      p_companion_user_id,
      v_status_code,
      case when v_waitlist_start is null then null else v_waitlist_start + 1 end,
      v_group_id
    );

  select *
  into v_result
  from public.event_registrations
  where event_id = p_event_id
    and user_id = v_user_id;

  return v_result;
end;
$$;

revoke all on function public.register_pair_for_event(bigint, uuid) from public, anon;
grant execute on function public.register_pair_for_event(bigint, uuid) to authenticated;

create or replace function public.unregister_pair_from_event(p_event_id bigint)
returns public.event_registrations
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_group_id bigint;
  v_result public.event_registrations;
begin
  if v_user_id is null then
    raise exception 'authentication_required';
  end if;

  perform 1 from public.events where id = p_event_id for update;
  if not found then
    raise exception 'event_not_found';
  end if;

  select registration.*
  into v_result
  from public.event_registrations registration
  where registration.event_id = p_event_id
    and registration.user_id = v_user_id
  for update;

  if not found then
    raise exception 'registration_not_found';
  end if;

  v_group_id := v_result.registration_group_id;
  if v_group_id is null then
    raise exception 'paired_registration_not_found';
  end if;

  delete from public.event_registration_groups where id = v_group_id;
  perform private.rebalance_event_waitlist(p_event_id);

  return v_result;
end;
$$;

revoke all on function public.unregister_pair_from_event(bigint) from public, anon;
grant execute on function public.unregister_pair_from_event(bigint) to authenticated;

create or replace function public.admin_delete_pair_registration(p_registration_id bigint)
returns public.event_registrations
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_id uuid := auth.uid();
  v_group_id bigint;
  v_result public.event_registrations;
begin
  if v_actor_id is null then
    raise exception 'authentication_required';
  end if;

  if not exists (
    select 1 from public.profiles where id = v_actor_id and role = 'admin'
  ) then
    raise exception 'admin_required';
  end if;

  select registration.*
  into v_result
  from public.event_registrations registration
  where registration.id = p_registration_id
  for update;

  if not found then
    raise exception 'registration_not_found';
  end if;

  v_group_id := v_result.registration_group_id;
  if v_group_id is null then
    raise exception 'paired_registration_not_found';
  end if;

  perform 1 from public.events where id = v_result.event_id for update;
  delete from public.event_registration_groups where id = v_group_id;
  perform private.rebalance_event_waitlist(v_result.event_id);

  return v_result;
end;
$$;

revoke all on function public.admin_delete_pair_registration(bigint) from public, anon;
grant execute on function public.admin_delete_pair_registration(bigint) to authenticated;

commit;
